name: finance_flow
description: App for manage your finance
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.5
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_fonts: ^6.3.3
  go_router: ^17.0.0
  flutter_svg: ^2.0.9
  fl_chart: ^1.1.1
  formz: ^0.8.0
  intl: ^0.18.0
  uuid: ^4.5.2
  equatable: ^2.0.5
  get_it: ^9.2.0
  json_serializable_uuid_converter: ^1.0.0
  credit_card_form: ^1.0.1
  collection: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  freezed: ^3.2.3
#  hive_generator: any
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
      - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
